export const defaultProjects = [
  { title: 'Smartcut', sub: 'Men’s Salon Website', desc: 'A polished barbershop website for Smartcut Rahwali, featuring services, appointments, reviews, and contact options.', tech: ['React', 'Responsive Design', 'Vercel'], category: 'Salon', color: '#C9A84C', year: '2025', link: 'https://smartcut-ashy.vercel.app/', image: 'https://image.thum.io/get/width/600/crop/800/https://smartcut-ashy.vercel.app/' },
  { title: 'Ali Ecom', sub: 'Social Media Marketing Portfolio', desc: 'A high-conversion portfolio website for a Meta ads and social media expert, showcasing results, services, and client work.', tech: ['React', 'Marketing UI', 'Vercel'], category: 'Marketing', color: '#E53935', year: '2025', link: 'https://aliecom.vercel.app/', image: 'https://image.thum.io/get/width/600/crop/800/https://aliecom.vercel.app/' },
  { title: 'SmartPOS', sub: 'Point of Sale Dashboard', desc: 'A modern point-of-sale dashboard with sales insights, order management, product tracking, reports, and stock alerts.', tech: ['React', 'Dashboard UI', 'Charts'], category: 'POS', color: '#22C55E', year: '2025', link: 'https://pos-coral-seven-16.vercel.app/', image: 'https://image.thum.io/get/width/600/crop/800/https://pos-coral-seven-16.vercel.app/' },
  { title: 'Shiza Salon', sub: 'Beauty & Bridal Salon Website', desc: 'An elegant salon website designed for beauty, bridal, hair, skin, and self-care services with appointment booking.', tech: ['React', 'Responsive Design', 'Vercel'], category: 'Salon', color: '#D4A373', year: '2025', link: 'https://shiza-salon.vercel.app/', image: 'https://image.thum.io/get/width/600/crop/800/https://shiza-salon.vercel.app/' },
  { title: 'Best Hair Salon', sub: 'Premium Men’s Grooming Website', desc: 'A refined men’s grooming website for showcasing services and helping customers reserve a chair online.', tech: ['React', 'Responsive Design', 'Vercel'], category: 'Salon', color: '#C9A84C', year: '2025', link: 'https://best-hair.vercel.app/', image: 'https://image.thum.io/get/width/600/crop/800/https://best-hair.vercel.app/' },
  { title: 'Standard General', sub: 'Construction Company Website', desc: 'A professional construction company website presenting services, completed work, and estimate request options.', tech: ['React', 'Responsive Design', 'Vercel'], category: 'Business', color: '#C99A3D', year: '2025', link: 'https://standard-general.vercel.app/', image: 'https://image.thum.io/get/width/600/crop/800/https://standard-general.vercel.app/' },
]

export const defaultTeamMembers = [
  { name: 'Hassan Noor', role: 'CEO & Founder', bio: 'Visionary leader with 10+ years in software engineering. Founded Devcorex with the mission to deliver world-class digital solutions that stand the test of time.', skills: ['Strategy', 'Architecture', 'Leadership', 'Innovation'], initials: 'HN', featured: true },
  { name: 'Usman Zafar', role: 'Senior Software Developer & graphic designer', bio: 'Former Google engineer with deep expertise in distributed systems and cloud architecture. Leads our technical direction and engineering excellence.', skills: ['UX', 'UI', 'Motion', 'Brand', 'Graphic Design', 'React,typescript', 'JavaScript', 'AI', 'Node'], initials: 'UZ' },
  { name: 'Umair Azam', role: 'Senior frontend Developer', bio: 'Award-winning UX/UI designer who blends art with user psychology to create interfaces that captivate and convert.', skills: ['UX', 'UI', 'Motion', 'Brand', 'javascript', 'React', 'Next.js', 'Tailwind CSS'], initials: 'UA' },
  { name: 'Ali Raza', role: 'Full-stack Developer', bio: 'Full-stack powerhouse who orchestrates complex engineering projects with military precision and creative flair.', skills: ['React', 'Node', 'Nuxt.js', 'AWS', 'MySQL', 'MongoDB', 'Next.js', 'Tailwind CSS'], initials: 'AR' },
  { name: 'Hamza Arsahd', role: 'Software Engineer', bio: 'PhD in Machine Learning from LUMS. Builds intelligent systems that transform raw data into business-changing insights.', skills: ['React', 'Node', 'Nuxt.js', 'AWS', 'MySQL', 'MongoDB', 'Next.js'], initials: 'HA' },
]

export const defaultSettings = [
  { key: 'contact_email', value: 'hassannoor2309@gmail.com' },
  { key: 'location', value: 'Gujranwala, Pakistan' },
]
